# Generated by Django 5.0.14 on 2025-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_images',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
